<?php

namespace MoviesBundle\Repository;

/**
 * HostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostRepository extends \Doctrine\ORM\EntityRepository
{
}
